apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: 3htp-dokuwiki
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: 3htp-dokuwiki
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: alvasquez/mydokuwiki:mydb
        name: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_DATABASE
      imagePullSecrets:
        - name: myregistrykey
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-volume-claim