apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  namespace: 3HTP-Dokuwiki
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi


############################### with local volume ##############################################
