apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: 3htp-dokuwiki
spec:
  type: NodePort
  selector:
    app: dokuwiki
  ports:
  - nodePort: 31080
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokuwiki
  namespace: 3htp-dokuwiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
    spec:
      containers:
      - image: alvasquez/mydokuwiki:dokuwiki
        name: server
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-storage
          mountPath: /var/www/html
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dokuwiki-config
              key: MYSQL_DATABASE
      imagePullSecrets:
        - name: myregistrykey
      volumes:
      - name: web-storage
        persistentVolumeClaim:
          claimName: dokuwiki-volume-claim