apiVersion: v1
kind: PersistentVolume
metadata:
  name: dokuwiki-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/dokuwiki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki-volume-claim
  namespace: 3htp-dokuwiki
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi