apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-grafana
  namespace: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/3htp-kubernetes/QA/grafana




